import { FAIXAS_IDADE_EXEMPLO, REGRAS_EXEMPLO, TODOS_OS_DIAS, type Modelo } from './schema';

/** Buffet em domicílio. Valores de exemplo, para o dono trocar. */
export const modeloDomicilio: Modelo = {
  segmento: 'domicilio',
  nome: 'Buffet em domicílio',
  tiposEvento: [
    { chave: 'aniversario', nome: 'Aniversário', icone: 'cake' },
    { chave: 'churrasco', nome: 'Churrasco', icone: 'flame' },
    { chave: 'confraternizacao', nome: 'Confraternização', icone: 'users' },
    { chave: 'corporativo', nome: 'Corporativo', icone: 'briefcase' },
  ],
  espacos: [
    {
      chave: 'local-cliente',
      nome: 'No local do cliente',
      capacidadeMax: 500,
      noLocalDoCliente: true,
    },
  ],
  turnos: [
    {
      chave: 'almoco',
      nome: 'Almoço',
      horaInicio: '12:00',
      duracaoMin: 240,
      diasSemana: TODOS_OS_DIAS,
    },
    {
      chave: 'noite',
      nome: 'Noite',
      horaInicio: '19:00',
      duracaoMin: 240,
      diasSemana: TODOS_OS_DIAS,
    },
  ],
  ajustesDia: [
    { diaSemana: 6, ajusteBp: 1000 },
    { diaSemana: 0, ajusteBp: 1000 },
  ],
  faixasIdade: FAIXAS_IDADE_EXEMPLO,
  pacotes: [
    {
      chave: 'salgados',
      nome: 'Salgados',
      subtitulo: 'Salgados fritos na hora',
      descricao: 'Salgados variados, fritos no local, e refrigerante.',
      destaque: false,
      modeloPreco: 'por_pessoa',
      precoPessoaCentavos: 4500,
      valorExcedenteCentavos: null,
      faixasPreco: [],
      minConvidados: 20,
      maxConvidados: 300,
      duracaoInclusaMin: 240,
      valorHoraExtraCentavos: 40000,
      tiposEvento: [],
      secoes: [
        { nome: 'Salgados', itens: ['Coxinha', 'Kibe', 'Bolinha de queijo', 'Risole', 'Pastel'] },
        { nome: 'Bebidas', itens: ['Refrigerante', 'Água'] },
      ],
    },
    {
      chave: 'massas',
      nome: 'Massas',
      subtitulo: 'O mais escolhido',
      descricao: 'Estação de massas com molhos à escolha e salada.',
      destaque: true,
      modeloPreco: 'por_pessoa',
      precoPessoaCentavos: 5500,
      valorExcedenteCentavos: null,
      faixasPreco: [],
      minConvidados: 20,
      maxConvidados: 300,
      duracaoInclusaMin: 240,
      valorHoraExtraCentavos: 45000,
      tiposEvento: [],
      secoes: [
        { nome: 'Massas', itens: ['Penne', 'Talharim', 'Nhoque'] },
        { nome: 'Molhos', itens: ['Sugo', 'Branco', 'Bolonhesa', 'Pesto'] },
        { nome: 'Acompanhamentos', itens: ['Salada verde', 'Pão de alho'] },
      ],
    },
    {
      chave: 'churrasco',
      nome: 'Churrasco',
      subtitulo: 'Churrasqueiro e carnes selecionadas',
      descricao: 'Churrasco completo com churrasqueiro, carnes e acompanhamentos.',
      destaque: false,
      modeloPreco: 'por_pessoa',
      precoPessoaCentavos: 7500,
      valorExcedenteCentavos: null,
      faixasPreco: [],
      minConvidados: 20,
      maxConvidados: 300,
      duracaoInclusaMin: 240,
      valorHoraExtraCentavos: 55000,
      tiposEvento: [],
      secoes: [
        { nome: 'Carnes', itens: ['Picanha', 'Fraldinha', 'Linguiça', 'Coração de frango'] },
        { nome: 'Acompanhamentos', itens: ['Farofa', 'Vinagrete', 'Arroz', 'Pão de alho'] },
      ],
    },
  ],
  opcionais: [
    {
      chave: 'garcom-extra',
      nome: 'Garçom extra',
      descricao: 'Garçom adicional durante toda a festa.',
      cobranca: 'por_unidade',
      precoCentavos: 22000,
      qtdMin: 1,
      qtdMax: 10,
      pacotesCompativeis: [],
      pacotesInclusos: [],
      tiposEvento: [],
    },
    {
      chave: 'louca',
      nome: 'Louça',
      descricao: 'Pratos, talheres e copos de vidro.',
      cobranca: 'por_pessoa',
      precoCentavos: 600,
      qtdMin: 1,
      qtdMax: 1,
      pacotesCompativeis: [],
      pacotesInclusos: [],
      tiposEvento: [],
    },
    {
      chave: 'bebidas',
      nome: 'Bebidas',
      descricao: 'Refrigerante, suco e água à vontade.',
      cobranca: 'por_pessoa',
      precoCentavos: 1200,
      qtdMin: 1,
      qtdMax: 1,
      pacotesCompativeis: [],
      pacotesInclusos: [],
      tiposEvento: [],
    },
  ],
  faixasDeslocamento: [],
  regras: {
    ...REGRAS_EXEMPLO,
    deslocamentoModelo: 'por_km',
    deslocamentoKmGratis: 20,
    deslocamentoValorKmCentavos: 300,
  },
};
