import { FAIXAS_IDADE_EXEMPLO, REGRAS_EXEMPLO, type Modelo } from './schema';

/** Buffet de casamento e eventos com salão. Valores de exemplo, para o dono trocar. */
export const modeloEventos: Modelo = {
  segmento: 'eventos',
  nome: 'Casamento e eventos',
  tiposEvento: [
    { chave: 'casamento', nome: 'Casamento', icone: 'heart' },
    { chave: '15-anos', nome: '15 anos', icone: 'sparkles' },
    { chave: 'formatura', nome: 'Formatura', icone: 'graduation-cap' },
    { chave: 'corporativo', nome: 'Corporativo', icone: 'briefcase' },
  ],
  espacos: [{ chave: 'salao', nome: 'Salão', capacidadeMax: 250, noLocalDoCliente: false }],
  turnos: [
    {
      chave: 'noite',
      nome: 'Noite',
      horaInicio: '20:00',
      duracaoMin: 300,
      diasSemana: [4, 5, 6, 0],
    },
  ],
  ajustesDia: [{ diaSemana: 5, ajusteBp: -1000 }],
  faixasIdade: FAIXAS_IDADE_EXEMPLO,
  pacotes: [
    {
      chave: 'classico',
      nome: 'Clássico',
      subtitulo: 'Jantar completo',
      descricao: 'Entrada, dois pratos principais, sobremesa e bebidas não alcoólicas.',
      destaque: false,
      modeloPreco: 'por_pessoa',
      precoPessoaCentavos: 12000,
      valorExcedenteCentavos: null,
      faixasPreco: [],
      minConvidados: 50,
      maxConvidados: 250,
      duracaoInclusaMin: 300,
      valorHoraExtraCentavos: 120000,
      tiposEvento: [],
      secoes: [
        { nome: 'Entrada', itens: ['Salada caprese', 'Canapés variados'] },
        {
          nome: 'Prato principal',
          itens: ['Filé ao molho madeira', 'Frango ao limão', 'Arroz com amêndoas'],
        },
        { nome: 'Sobremesa', itens: ['Pudim de leite', 'Mousse de maracujá'] },
      ],
    },
    {
      chave: 'especial',
      nome: 'Especial',
      subtitulo: 'O mais escolhido',
      descricao: 'Coquetel de recepção, jantar com três opções e mesa de frutas.',
      destaque: true,
      modeloPreco: 'por_pessoa',
      precoPessoaCentavos: 16500,
      valorExcedenteCentavos: null,
      faixasPreco: [],
      minConvidados: 50,
      maxConvidados: 250,
      duracaoInclusaMin: 300,
      valorHoraExtraCentavos: 150000,
      tiposEvento: [],
      secoes: [
        { nome: 'Coquetel', itens: ['Mini acarajé', 'Camarão empanado', 'Bruschetta'] },
        {
          nome: 'Prato principal',
          itens: ['Medalhão ao funghi', 'Salmão grelhado', 'Risoto de limão siciliano'],
        },
        { nome: 'Sobremesa', itens: ['Petit gâteau', 'Mesa de frutas'] },
      ],
    },
    {
      chave: 'gala',
      nome: 'Gala',
      subtitulo: 'Experiência completa',
      descricao: 'Coquetel volante, jantar empratado, mesa de doces finos e ilha de café.',
      destaque: false,
      modeloPreco: 'por_pessoa',
      precoPessoaCentavos: 23000,
      valorExcedenteCentavos: null,
      faixasPreco: [],
      minConvidados: 50,
      maxConvidados: 250,
      duracaoInclusaMin: 300,
      valorHoraExtraCentavos: 200000,
      tiposEvento: [],
      secoes: [
        {
          nome: 'Coquetel volante',
          itens: ['Tartar de salmão', 'Mini burger de costela', 'Dadinho de tapioca'],
        },
        {
          nome: 'Jantar empratado',
          itens: ['Entrada da estação', 'Filé mignon com purê trufado', 'Sobremesa do chef'],
        },
        { nome: 'Ilha de café', itens: ['Café espresso', 'Chás', 'Petit fours'] },
      ],
    },
  ],
  opcionais: [
    {
      chave: 'bar-drinks',
      nome: 'Bar de drinks',
      descricao: 'Bartender e drinks clássicos durante a festa.',
      cobranca: 'por_pessoa',
      precoCentavos: 3500,
      qtdMin: 1,
      qtdMax: 1,
      pacotesCompativeis: [],
      pacotesInclusos: [],
      tiposEvento: [],
    },
    {
      chave: 'doces-finos',
      nome: 'Mesa de doces finos',
      descricao: 'Mesa com doces finos e bem-casados.',
      cobranca: 'fixo',
      precoCentavos: 180000,
      qtdMin: 1,
      qtdMax: 1,
      pacotesCompativeis: [],
      pacotesInclusos: ['gala'],
      tiposEvento: [],
    },
    {
      chave: 'hora-extra-bar',
      nome: 'Hora extra de bar',
      descricao: 'Bar aberto por mais tempo depois do horário do pacote.',
      cobranca: 'por_hora',
      precoCentavos: 60000,
      qtdMin: 1,
      qtdMax: 3,
      pacotesCompativeis: [],
      pacotesInclusos: [],
      tiposEvento: [],
    },
  ],
  faixasDeslocamento: [],
  regras: REGRAS_EXEMPLO,
};
