import { FAIXAS_IDADE_EXEMPLO, REGRAS_EXEMPLO, TODOS_OS_DIAS, type Modelo } from './schema';

/** Buffet infantil com espaço próprio. Valores de exemplo, para o dono trocar. */
export const modeloInfantil: Modelo = {
  segmento: 'infantil',
  nome: 'Buffet infantil com espaço',
  tiposEvento: [
    { chave: 'aniversario-infantil', nome: 'Aniversário infantil', icone: 'party-popper' },
    { chave: 'cha-revelacao', nome: 'Chá revelação', icone: 'baby' },
    { chave: 'batizado', nome: 'Batizado', icone: 'church' },
  ],
  espacos: [
    {
      chave: 'salao-principal',
      nome: 'Salão principal',
      capacidadeMax: 120,
      noLocalDoCliente: false,
    },
  ],
  turnos: [
    {
      chave: 'almoco',
      nome: 'Almoço',
      horaInicio: '11:00',
      duracaoMin: 240,
      diasSemana: TODOS_OS_DIAS,
    },
    {
      chave: 'tarde',
      nome: 'Tarde',
      horaInicio: '15:00',
      duracaoMin: 240,
      diasSemana: TODOS_OS_DIAS,
    },
    {
      chave: 'noite',
      nome: 'Noite',
      horaInicio: '19:00',
      duracaoMin: 240,
      diasSemana: TODOS_OS_DIAS,
    },
  ],
  ajustesDia: [
    { diaSemana: 1, ajusteBp: -1500 },
    { diaSemana: 2, ajusteBp: -1500 },
    { diaSemana: 3, ajusteBp: -1500 },
    { diaSemana: 4, ajusteBp: -1500 },
    { diaSemana: 6, ajusteBp: 1000 },
  ],
  faixasIdade: FAIXAS_IDADE_EXEMPLO,
  pacotes: [
    {
      chave: 'alegria',
      nome: 'Alegria',
      subtitulo: 'O essencial para uma festa gostosa',
      descricao: 'Salgados fritos na hora, bebidas, doces e bolo.',
      destaque: false,
      modeloPreco: 'por_faixa',
      precoPessoaCentavos: null,
      valorExcedenteCentavos: 7500,
      faixasPreco: [
        { ateConvidados: 30, valorCentavos: 290000 },
        { ateConvidados: 50, valorCentavos: 390000 },
        { ateConvidados: 80, valorCentavos: 560000 },
      ],
      minConvidados: 15,
      maxConvidados: 120,
      duracaoInclusaMin: 240,
      valorHoraExtraCentavos: 35000,
      tiposEvento: [],
      secoes: [
        {
          nome: 'Salgados',
          itens: ['Coxinha', 'Bolinha de queijo', 'Risole de carne', 'Enroladinho de salsicha'],
        },
        { nome: 'Bebidas', itens: ['Refrigerante', 'Suco natural', 'Água'] },
        { nome: 'Doces', itens: ['Brigadeiro', 'Beijinho'] },
        { nome: 'Bolo', itens: ['Bolo de chocolate com brigadeiro'] },
      ],
    },
    {
      chave: 'super',
      nome: 'Super',
      subtitulo: 'O mais escolhido',
      descricao: 'Mais variedade de salgados, prato quente e mesa de doces.',
      destaque: true,
      modeloPreco: 'por_faixa',
      precoPessoaCentavos: null,
      valorExcedenteCentavos: 8500,
      faixasPreco: [
        { ateConvidados: 30, valorCentavos: 340000 },
        { ateConvidados: 50, valorCentavos: 450000 },
        { ateConvidados: 80, valorCentavos: 650000 },
      ],
      minConvidados: 15,
      maxConvidados: 120,
      duracaoInclusaMin: 240,
      valorHoraExtraCentavos: 45000,
      tiposEvento: [],
      secoes: [
        { nome: 'Entradas', itens: ['Mini pizza', 'Pão de queijo'] },
        { nome: 'Salgados', itens: ['Coxinha', 'Kibe', 'Esfiha', 'Empadinha', 'Risole de queijo'] },
        { nome: 'Prato quente', itens: ['Mini hambúrguer', 'Batata frita'] },
        { nome: 'Bebidas', itens: ['Refrigerante', 'Suco natural', 'Água'] },
        { nome: 'Doces', itens: ['Brigadeiro', 'Beijinho', 'Cajuzinho', 'Bicho de pé'] },
      ],
    },
    {
      chave: 'encanto',
      nome: 'Encanto',
      subtitulo: 'Completo, com bolo cenográfico',
      descricao: 'Tudo do Super, mais finger foods, doces finos e bolo cenográfico.',
      destaque: false,
      modeloPreco: 'por_faixa',
      precoPessoaCentavos: null,
      valorExcedenteCentavos: 10500,
      faixasPreco: [
        { ateConvidados: 30, valorCentavos: 420000 },
        { ateConvidados: 50, valorCentavos: 560000 },
        { ateConvidados: 80, valorCentavos: 810000 },
      ],
      minConvidados: 15,
      maxConvidados: 120,
      duracaoInclusaMin: 240,
      valorHoraExtraCentavos: 60000,
      tiposEvento: [],
      secoes: [
        { nome: 'Finger foods', itens: ['Mini quiche', 'Bruschetta', 'Mini wrap'] },
        { nome: 'Salgados', itens: ['Coxinha', 'Kibe', 'Esfiha', 'Empadinha', 'Croquete'] },
        { nome: 'Prato quente', itens: ['Escondidinho', 'Mini hambúrguer', 'Batata rústica'] },
        { nome: 'Bebidas', itens: ['Refrigerante', 'Suco natural', 'Água aromatizada'] },
        { nome: 'Doces finos', itens: ['Brigadeiro gourmet', 'Trufa', 'Camafeu', 'Bombom de uva'] },
      ],
    },
  ],
  opcionais: [
    {
      chave: 'mesa-tematica',
      nome: 'Mesa temática',
      descricao: 'Decoração da mesa do bolo no tema da festa.',
      cobranca: 'fixo',
      precoCentavos: 60000,
      qtdMin: 1,
      qtdMax: 1,
      pacotesCompativeis: [],
      pacotesInclusos: [],
      tiposEvento: [],
    },
    {
      chave: 'personagem',
      nome: 'Personagem vivo',
      descricao: 'Personagem animando a festa por 1 hora.',
      cobranca: 'por_unidade',
      precoCentavos: 35000,
      qtdMin: 1,
      qtdMax: 3,
      pacotesCompativeis: [],
      pacotesInclusos: [],
      tiposEvento: ['aniversario-infantil'],
    },
    {
      chave: 'recreacao-extra',
      nome: 'Recreação extra',
      descricao: 'Monitor de recreação adicional.',
      cobranca: 'por_hora',
      precoCentavos: 18000,
      qtdMin: 1,
      qtdMax: 4,
      pacotesCompativeis: [],
      pacotesInclusos: [],
      tiposEvento: [],
    },
    {
      chave: 'bolo-cenografico',
      nome: 'Bolo cenográfico',
      descricao: 'Bolo decorativo para as fotos.',
      cobranca: 'fixo',
      precoCentavos: 25000,
      qtdMin: 1,
      qtdMax: 1,
      pacotesCompativeis: [],
      pacotesInclusos: ['encanto'],
      tiposEvento: [],
    },
  ],
  faixasDeslocamento: [],
  regras: REGRAS_EXEMPLO,
};
